

<section class="content">
<h1>ORDEN A BUSCAR</h1> 

         
          <form class="form-horizontal">
              <div class="box-body primary">
                
                  <div class="form-horizontal">
                  <label for="exp">Exp.Penal:</label>
                  <input type="number"   autocomplete="on" class="form-control" id="exp" placeholder="Inserte Exp.penal">
                </div>
                  
                  <div class="form-horizontal">
                  <label for="año">Año Penal:</label>
                  <input type="number" class="form-control" id="año" placeholder="Inserte Numero Penal">
                </div>
                  
                <div class="form-horizontal">
                <label>Juzgado:</label>
                <select class="form-control select2" style="width: 100%;">
                  <option selected="selected">Seleccione</option>
                  <option>1.- JUZGADO PRIMERO PENAL OAXACA </option>
                  <option>2.- JUZGADO SEGUNDO PENAL OAXACA</option>
                  <option>3.- JUZGADO TERCERO PENAL OAXACA</option>
                  <option>4.- JUZGADO CUARTO PENAL OAXACA</option>
                  <option>5.- JUZGADO QUINTO PENAL OAXACA</option>
                  <option>6.- JUZGADO SEXTO PENAL OAXACA</option>
                </select>
              </div>
                  
                   <div class="form-horizontal">
                <label>Tipo de Orden:</label>
                <select class="form-control select2" style="width: 100%;">
                  <option selected="selected">Seleccione</option>
                  <option>APREHENSION </option>
                  <option>COMPARESENSIA</option>
                  <option>REAPREHENSION</option>
                  
                  
                </select>
      <div class="box-body">
      	<div class="col-lg-3 col-md-3 pull-right">
      		<button type="reset" class="btn btn-warning btn-flat" style="margin-right:10px;">BUSCAR</button>
        	<button type="submit" value="formulario" name="formulario" class="btn btn-success btn-flat">CANCELAR</button>
        </div> 
      </div> 
                   </div>
              </div>
          </form>

</section>