<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://wiki.kumbiaphp.com/Licencia
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@kumbiaphp.com so we can send you a copy immediately.
 *
 * Paginador "classic" para aplicaciones
 *
 * Parametros del paginador:
 *   page: objeto obtenido al invocar al paginador
 *   show: numero de paginas que se mostraran en el paginador
 *   url: url para la accion que efectua la paginacion, por defecto "module/controller/page/"
 *        y se envia por parametro el numero de pagina
 * 
 * @category   Kumbia
 * @package    Partials 
 * @copyright  Copyright (c) 2005-2012 Kumbia Team (http://www.kumbiaphp.com)
 * @license    http://wiki.kumbiaphp.com/Licencia     New BSD License
 */

if(!isset($url)) {
    extract(Router::get());
    $url = "$controller/page";
    if($module) {
        $url = "$module/$url";
    }
}
    
if(!isset($show)) {
    $show = 10;
}

if(!isset($modelo)) {
    $modelo = 'datos';
}
    
$half = floor($show/2);
    
// Calculando el inicio de paginador centrado
if ($page->current <= $half) {
    $start = 1;
} elseif (($page->total - $page->current)<$half) {
    $start = $page->total - $show + 1;
    if($start < 1) $start = 1;
} else {
    $start = $page->current - $half;
}

$s_item = $page->per_page*($page->current-1) + 1;
$e_item = $s_item + count($page->items) - 1;
?>

<div class="paginator">
    <?php 
		if($page->prev)
		echo Html::link("$url/", 'Primera', 'title="Ir a la primer p&#225;gina" class="nextprev" rel="prev"')." | "; // Se coloca el enlace sin número de página para la pagina 1
		if($page->prev==1)			
		echo Html::link("$url/", '<<', 'title="Ir a la p&#225;gina anterior" class="nextprev" rel="prev"')." | "; // Se coloca el enlace sin número de página para la pagina 1
        elseif($page->prev) echo Html::link("$url/$page->prev/", 'Anterior', 'title="Ir a la pág. anterior" class="nextprev" rel="prev"')." | "; ?>

	
	<?php 
		if ($page->total>1){
			if($start==1){ //se coloca el link sin número de página para la página 1
				$start = 2;
				$show -= 1;
				echo " | ".($page->current==1 ? "<strong>1</strong>" : Html::link("$url/", '1'));
			}
		}
	?>
        
    <?php for($i=$start; $i<=$page->total && $i<($start + $show); $i++): ?>
        <?php echo " | ".($i==$page->current ? "<strong>$i</strong>" : Html::link("$url/$i/", $i)) ?>
    <?php endfor ?>
	<?php if ($page->total>0) {?>
	 | 
    <?php if($page->next){
		echo Html::link("$url/$page->next/", '>>', 'title="Ir a la p&#225;gina siguiente" class="nextprev" rel="next"')." | ";
		echo Html::link("$url/$page->total/", '&#218;ltima', 'title="Ir a la &#250;ltima p&#225;gina" class="nextprev" rel="next"');
		}
	?><br>
	P&#225;gina <?php echo $page->current ?> de <?php echo $page->total ?><br>
    <?php echo $modelo; ?> desde el <?php echo $s_item ?> hasta el <?php echo $e_item ?> de un total de <?php echo $page->count; ?>
	<?php } 
		else {
			echo "No se encontraron $modelo";
		}
	?>
</div>
