       <section class="content">
         <h2>NUEVA ORDEN DE APREHENSIÓN</h2> 
          <form class="form-horizontal">
            <div class="box-body">                  
                <div class="form-group">
                    <label for="exp">Expediente Penal : </label>
                    <input type="number" class="form-control" id="exp" placeholder="Inserte expediente penal">
                </div>
                <div class="form-group">
                    <label for="año">Año Penal : </label>
                    <input type="number" class="form-control" id="año" placeholder="Inserte numero penal">
                </div>
                <div class="form-group">
                    <label class="ingreso">Juzgado : </label>
                    <?php echo Form::dbSelect('juzgados_id','juzgado',array('juzgados','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>
                </div>
                <div class="form-group">
                    <label>Tipo de Orden:</label>
                    <?php echo Form::dbSelect('tiposoa_id','descripcion',array('tiposoa','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>                   </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-google ">INICIAR</button>
                    <button  class="btn btn-info pull-right">CANCELAR</button>
                </div>
             </div>
          </form>
      </section>
                              
    