  <section class="content">

      <div class="box box-primary">
              <h3 class="box-title">Nueva Orden de Aprehensión</h3>      
             <div class="box-body">                  
                <div class="col-md-6">
                    <label for="exp">Expediente Penal : </label>
                    <?php echo Form::number('exppenal','class="form-control" onblur="convierte(this)"') ?><br>
                </div>
                <div class="col-md-6">
                    <label for="año">Año Penal : </label>
                    <?php echo Form::number('anipenal','class="form-control" onblur="convierte(this)"') ?><br>
                </div>
                <div class="col-md-6">
                    <label class="ingreso">Juzgado : </label>
                    <?php echo Form::dbSelect('juzgados_id','juzgado',array('juzgados','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>
                </div>
                <div class="col-md-6">
                    <label>Tipo de Orden:</label>
                    <?php echo Form::dbSelect('tiposoa_id','descripcion',array('tiposoa','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>                   </div>
                </div>
                <div class="box-footer">
                <?php echo Form::submit("Iniciar",'class= "btn btn-primary", id="btnAccion"')?>
                <?php echo Form::close(); ?> 
              </div>
             </div>                   
 </section>