  <section class="content">
      <div class="box box-primary">
              <h3 class="box-title">Nueva Orden de Aprehensión</h3>
          <form class="form-horizontal">
            <div class="box-body">                  
                <div class="col-md-6">
                    <label for="exp">Expediente Penal : </label>
                    <input type="number" class="form-control" id="exp" placeholder="Inserte expediente penal">
                </div>
                <div class="col-md-6">
                    <label for="año">Año Penal : </label>
                    <input type="number" class="form-control" id="año" placeholder="Inserte numero penal">
                </div>
                <div class="col-md-6">
                    <label class="ingreso">Juzgado : </label>
                    <?php echo Form::dbSelect('juzgados_id','juzgados',array('juzgados','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>
                </div>
                <div class="col-md-6">
                    <label>Tipo de Orden:</label>
                    <?php echo Form::dbSelect('tiposoa_id','descripcion',array('tiposoa','listar'),'Seleccione','class="form-control select2" style="width: 100%"') ?>                   </div>
                </div>
                <div class="box-footer">
                <button type="submit" class="btn btn-primary">Aceptar</button>
              </div>
             </div>
          </form>
      </div>                              
 </section>